name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt
      run: sudo apt update & sudo apt-get install gcc-multilib g++-multilib
    - name: chmod
      run: chmod 777 premake5
    - name: premake
      run: ./premake5 --file=premake5.lua gmake2
    - name: gmake
      run: gmake -C project
    - name: gmake check
      run: gmake check -C project
    - name: gmake distcheck
      run: gmake distcheck -C project
