name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt
    - run: sudo apt update & sudo apt install gcc-multilib g++-multilib
    - name: chmod
      run: chmod 777 premake5
    - name: premake
      run: ./premake5 gmake2
    - name: make
      run: make -C project
    - name: make check
      run: make check -C project
    - name: make distcheck
      run: make distcheck -C project
